// Generated by CoffeeScript 1.6.2
var height, main, makeColor, moveLetter, width, yo;

$(width = window.innerWidth, height = window.innerHeight, moveLetter = function($elt) {
  var $child;

  $elt.css({
    top: Math.random() * (height - 50),
    left: Math.random() * (width - 50)
  });
  $child = $($elt.children()[0]);
  return $child.css({
    'font-size': Math.random() * 100 + 100
  });
}, makeColor = function() {
  var a, hex, i, nums, _i, _len;

  hex = '#';
  nums = (function() {
    var _i, _results;

    _results = [];
    for (i = _i = 0; _i <= 5; i = ++_i) {
      _results.push(Math.floor(Math.random() * 14).toString(16));
    }
    return _results;
  })();
  for (_i = 0, _len = nums.length; _i < _len; _i++) {
    a = nums[_i];
    hex += a;
  }
  return hex;
}, yo = function() {
  var colory, faa, _i, _len, _ref, _results;

  _ref = $('div');
  _results = [];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    faa = _ref[_i];
    colory = makeColor();
    console.log(colory);
    _results.push($(faa).css('color', colory));
  }
  return _results;
}, main = function() {
  var elt, _i, _len, _ref, _results;

  _ref = $('div');
  _results = [];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    elt = _ref[_i];
    _results.push(moveLetter($(elt)));
  }
  return _results;
}, setTimeout(yo, 10), setInterval(main, 400));
